### ISSUE TITLE
JSON format [BUG]

### ISSUE THREAD

**Issue by Damix48** [Cyb3r-Jak3/html5validator-action#13]
**Describe the bug**
In JSON output use `'` istead of `"`

**What actually happens**
```
"message": "End tag for "body" seen, but there were unclosed elements.",
```

**Expected behavior**
```
"message": "End tag for 'body' seen, but there were unclosed elements.",
```

**Comment by Cyb3r-Jak3** [comment]
@Damix48 What is the use case? Are you parsing the JSON output?

At first glance, this seems like something for the linter [html5validator](https://github.com/svenkreiss/html5validator) and not for this action.

**Comment by Damix48** [comment]
Yes, I'm parsing JSON.

> At first glance, this seems like something for the linter [html5validator](https://github.com/svenkreiss/html5validator) and not for this action.

You are right
