### ISSUE TITLE
Workflow seems to run into an error when there is no issues with my website.

### ISSUE THREAD

**Issue by WindowsSystemAdmin** [Cyb3r-Jak3/html5validator-action#30]
### If there is an issue with your workflow then please include a log link or output as well as your full workflow config file
Hello there, I ran into an issue with my workflow and the error seems to be this:
"file:/github/workspace/./index.html":11.1-11.7: error: Element "head" is missing a required instance of child element "title".
when in fact I have an element title in head.

<head>
	<title>Trade Tools - Figures Table</title>
</head>

**Comment by Cyb3r-Jak3** [comment]
Assuming that [this](https://github.com/WindowsSystemAdmin/research) is the repo you are using.

This issue that your [index.html](https://github.com/WindowsSystemAdmin/research/blob/main/index.html) file does not have `<title>` only the [ResearchResources.html](https://github.com/WindowsSystemAdmin/research/blob/main/ResearchResources.html) file does

**Comment by WindowsSystemAdmin** [comment]
ah yes your right thanks! I was up all night figuring this out!
