### ISSUE TITLE
Issue with git detecting repos

### ISSUE THREAD

**Issue by SystemsUser** [Cyb3r-Jak3/html5validator-action#31]
### If there is an issue with your workflow then please include a log link or output as well as your full workflow config file
 Hello there!
I am having an issue where I am getting git repository not found. when I set the root to pages/. Is this incorrect? I am not sure how to fix this.

**Comment by SystemsUser** [comment]
/usr/bin/docker run --name bcf094ec6ed3337cd432db4f4b83765cb2cc9_e228e1 --label 2bcf09 --workdir /github/workspace --rm -e INPUT_ROOT -e INPUT_LOG_LEVEL -e INPUT_CSS -e INPUT_CONFIG -e INPUT_EXTRA -e INPUT_FORMAT -e INPUT_BLACKLIST -e INPUT_SKIP_GIT_CHECK -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e GITHUB_STEP_SUMMARY -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/research/research":"/github/workspace" 2bcf09:4ec6ed3337cd432db4f4b83765cb2cc9
Running Validator
Error: There is no git respository detected

**Comment by SystemsUser** [comment]
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  HTMLCHECK:
    runs-on: ubuntu-latest
    steps:
    - run: lsb_release -a
    - run: uname -a
    - uses: actions/checkout@v3
    - name: HTML5Validator
      uses: Cyb3r-Jak3/html5validator-action@master
      with:
          root: pages
          log_level: INFO
          css: true
    - uses: actions/upload-artifact@v3
      with:
          name: log
          path: log.log

**Comment by Cyb3r-Jak3** [comment]
This issue appears to have emerged in the past week. Last week's test showed no issues ([Integration Test](https://github.com/Cyb3r-Jak3/html5validator-action/actions/runs/2142492253) & [Action Test](https://github.com/Cyb3r-Jak3/html5validator-action/actions/runs/2142409886)) and this week's test failed ([Integration Test](https://github.com/Cyb3r-Jak3/html5validator-action/actions/runs/2178549005) & [Action Test](https://github.com/Cyb3r-Jak3/html5validator-action/actions/runs/2178470419)) when there have been no commits in that time span.

**Comment by Cyb3r-Jak3** [comment]
Appears to be related to https://github.com/actions/checkout/issues/760

**Comment by Cyb3r-Jak3** [comment]
@SystemsUser Please try with version v7.1.1

**Comment by SystemsUser** [comment]
awesome ty :)

**Comment by SystemsUser** [comment]
thanks @Cyb3r-Jak3
