### ISSUE TITLE
[BUG] unauthorized: unauthenticated: User cannot be authenticated with the token provided | on pulling docker images

### ISSUE THREAD

**Issue by igormcsouza** [Cyb3r-Jak3/html5validator-action#34]
**Describe the bug**
Got an error when pulling image from docker (on the begining of the action)
```
 error pulling image configuration: download failed after attempts=1: unauthorized: unauthenticated: User cannot be authenticated with the token provided.
```

**To Reproduce**

1. Starts the job
2. As soon as the docker starts pooling the error comes

### What is the current *bug* behavior

What actually happens

**Expected behavior**
Pull the image and continue with the html check normaly

**Screenshots**
![image](https://user-images.githubusercontent.com/38996012/175024242-1dc2d70b-5a90-46ac-8f71-2ec76ac23db1.png)

**Additional context**
I already ran this action before, with no problems! [Here](https://github.com/igormcsouza/igormcsouza.github.io/runs/5694394371?check_suite_focus=true) is an example!

**Comment by igormcsouza** [comment]
Weird is that the image looks open https://github.com/cyb3r-jak3/html5validator-docker/pkgs/container/html5validator/23477120?tag=source-alpine

**Comment by Cyb3r-Jak3** [comment]
Hi @igormcsouza 
Can you try re-running your action again? The timing of it looks suspiciously like it could have been affected by an outage eariler today: https://www.githubstatus.com/incidents/10vm6ctn52gx

**Comment by igormcsouza** [comment]
It works now.. thanks for the help and support! :D
