### ISSUE TITLE
[FEATURE REQUEST] Compatibility with Bootstrap

### ISSUE THREAD

**Issue by MuffinKing-jpeg** [Cyb3r-Jak3/html5validator-action#35]
When the CSS file contains bootstrap it throws an error

It will be nice to have the ability to disable specific errors like "non-existing feature".
[Example](https://github.com/MuffinKing-jpeg/lesson-12/runs/7859879018?check_suite_focus=truel) of errors.

**Comment by Cyb3r-Jak3** [comment]
You can ignore errors with [html5validator](https://github.com/svenkreiss/html5validator), and it is something that should probably be implemented here. You can use a [config file](https://github.com/svenkreiss/html5validator/tree/main/html5validator/tests/config_files) with the current version of this action. One like this should get you started:
https://github.com/svenkreiss/html5validator/blob/main/html5validator/tests/config_files/ignore_and_ignorere.yaml

**Comment by ZeTheDeveloper** [comment]
Could you please guide me on using the the config file with the action? Do I create the config file and reference to it?

**Comment by MuffinKing-jpeg** [comment]
I tried to use a configuration file. It broke everything, but I found the problem, default parser for CSS3 only, but for bootstrap must be CSS3+SVG

**Comment by Cyb3r-Jak3** [comment]
Thanks for the update!
Sounds like a problem with https://github.com/validator/validator and not this action
