### ISSUE TITLE
Warning: The `set-output` command is deprecated and will be disabled soon

### ISSUE THREAD

**Issue by xavierfoucrier** [Cyb3r-Jak3/html5validator-action#38]
Hello 👋

Using the first time this Github Action and discovered there is **a warning notice in the action log** about `set-output`.

![image](https://user-images.githubusercontent.com/2471223/200033452-aeb4fced-8f13-4c81-bf24-2d165a73c882.png)

> See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands.

**Comment by xavierfoucrier** [comment]
@Cyb3r-Jak3 I just saw you fixed it in #36, but looks not?🤔

**Comment by Cyb3r-Jak3** [comment]
The fix is in version 7.2.0 (which I forgot to release). If you change to use that version, then the warning should no longer be there.

**Comment by xavierfoucrier** [comment]
@Cyb3r-Jak3 yup! Looks fine now, thanks for the fast reply. Closing the issue 🚀
