### ISSUE TITLE
Show output without having to upload the log file

### ISSUE THREAD

**Issue by davidfischer** [Cyb3r-Jak3/html5validator-action#4]
Based on this:

https://github.com/Cyb3r-Jak3/html5validator-action/blob/5ea5e43f8a724f0e3aa77da95d7802b185bc12a3/entrypoint.sh#L25

The output of validation isn't shown without uploading the log file. It would be nice to show it in addition to uploading the log file.

**Comment by davidfischer** [comment]
I'm not sure if you took this on but I was thinking about trying something like:

```
 html5validator --root "${INPUT_ROOT}" --log "${INPUT_LOG_LEVEL}" ${BuildARGS} 2>&1 | tee log.log
```

**Comment by Cyb3r-Jak3** [comment]
Yeah, that was my plan. Also just looking at getting the result exit code to match. With the use of tee the exit code is set from tee. Should be able to do it with something like `${PIPESTATUS[0]}`.

**Comment by davidfischer** [comment]
I don't think #5 quite solved things correctly.
![Screen Shot 2020-07-05 at 11 43 45 AM](https://user-images.githubusercontent.com/185043/86539910-3a053800-beb5-11ea-93d9-631c883e1735.png)
(this has a validation error but returned success)

I'm no expert on github actions, but based on my reading of [the docs](https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action#writing-the-action-code), I think that `echo ::set-output name=result::$result;` merely sets the variable for future actions to use. At some point, you need a command in the script  that returns a non-zero status code.

Maybe just set `set -o pipefail`?

**Comment by Cyb3r-Jak3** [comment]
@davidfischer Check now. I did the set -o pipeline and have added tests for invalid HTML.

**Comment by davidfischer** [comment]
Worked perfectly. Thanks a lot!
